### ISSUE TITLE
Homebrew Cask's default Caskroom location has changed

### ISSUE THREAD

**Issue by jeroenj** [chef-cookbooks/homebrew#100]
As per https://github.com/caskroom/homebrew-cask/pull/21857 the default location for the Caskroom has changed to `/usr/local/Caskroom` instead of `/opt/homebrew-cask/Caskroom`.

The cask recipe will always create the old directory: https://github.com/chef-cookbooks/homebrew/blob/ab010defa6d3cc4cbf9c83c4c097f6ac87ef7e1f/recipes/cask.rb#L29-L38

As long as the old directory exists cask will show a warning that you should migrate to the new location but it will keep using the old location. Since this recipe always creates the old location cask will keep on installing in the old location even if you have migrated to the new one.

One option would be to just change the directories in the cask recipe but I'm actually not sure if those directories should be created by that recipe. I'd think that cask would create them if they don't exist yet. But I'd have to investigate that.

**Comment by wendorf** [comment]
This should be fixed by #103

**Comment by jobster** [comment]
This is not fixed in the latest version available (2.1.0)! @wendorf can you please release a version that includes this change?  2.1.0 is now 7 months old, and it would be really nice if I didn't have to change my Cheffile so that it referenced tip of master explicitly.

Thanks!

**Comment by wendorf** [comment]
Sorry, @jobster. I don't control this repo. I echo the sentiment, though.

**Comment by aramprice** [comment]
Is there an ETA on releasing a version of the cookbook with the fix from https://github.com/chef-cookbooks/homebrew/pull/103?

**Comment by tas50** [comment]
This has been pushed up to Supermarket
