### ISSUE TITLE
HOMEBREW_CACHE replacement during installation?

### ISSUE THREAD

**Issue by ygini** [chef-cookbooks/homebrew#106]
### Cookbook version

2.1.0
### Chef-client version

12.12.15
### Platform Details

OS X 10.11.6 with chef-client run as service (created by chef-client resource)
### Scenario:

When deploying system, a kickstart script install chef and register workstation to my chef server and run content from a default role.

The kickstart occur when the target admin account owning the homebrew setup has never been logged to the Mac (installation done with https://github.com/MagerValp/CreateUserPkg)
### Steps to Reproduce:

Run the homebrew installation from chef-client run as a launchd service when the target admin as never been connected to the mac
### Expected Result:

homebrew should install and admin account should be OK
### Actual Result:

Due to HOMEBREW_CACHE localization, the installer create a partial home folder for the never logged admin.

When the admin authenticate after, the system will display a lot of errors saying that Library is broken. This is because home folder exist but is empty. So all OS X home folder creation system are blocked due to files in HOMEBREW_CACHE

Homebrew cookbook should play with env to avoid using cache folder in /Users but in /tmp for example.

**Comment by bdwyertech** [comment]
I don't think this is an issue with this cookbook, I think you should adjust your build scripts so the users are properly provisioned prior to running Homebrew as them.

**Comment by ygini** [comment]
Since provisioning home folder on OS X mean human based login I think this cookbook should be updated. 

Otherwise system automation is 100% useless if I need to have a human to be connected on the admin account before being able to run chef using home brew.

**Comment by cheeseplus** [comment]
Pretty sure given the timing of this issue that this was adjusted upstream as well in homebrew. Closing but please do open a new one with the repro steps if still present.
