### ISSUE TITLE
Installing casks from a URL

### ISSUE THREAD

**Issue by paulhanssen** [chef-cookbooks/homebrew#130]
### Cookbook version
4.3.0

### Chef-client version
13.6.4

### Platform Details
macOS 'High Sierra' 10.13.2 (17C205)

### Scenario:
Installing a cask from a URL fails

### Steps to Reproduce:
Trying this fails from a Chef cookbook:

`
homebrew_cask 'https://raw.githubusercontent.com/caskroom/homebrew-cask/3c3268942ff163d917245fbc68d26a5bcddf91de/Casks/virtualbox.rb'
`

### Expected Result:
It should install. The (raw) command itself works:

`
/usr/local/bin/brew cask install 'https://raw.githubusercontent.com/caskroom/homebrew-cask/3c3268942ff163d917245fbc68d26a5bcddf91de/Casks/virtualbox.rb'
`

### Actual Result:
The error reported is:

```
================================================================================
Recipe Compile Error in /Users/paul.hanssen/.chef/state/cache/cookbooks/sf_macos/recipes/developer.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option name's value https://raw.githubusercontent.com/caskroom/homebrew-cask/3c3268942ff163d917245fbc68d26a5bcddf91de/Casks/virtualbox.rb does not match regular expression /^[\w\/-]+$/
```

I believe the error occurs in the 'cask.rb' resource i.e.

`
property :name, String, regex: %r{^[\w/-]+$}, name_property: true # ~FC108
`

**Comment by tas50** [comment]
Is there a particular reason not to specify the cask by name since you're just pulling that from the standard source? We use the name for idempotency checks so we can't just use the URL. We still need to know the name.

**Comment by tas50** [comment]
Oh I see you're installing the older version. I think what we'd have to do is something like this

homebrew_cask 'virtualbox' do
 cask_def_uri 'https://raw.githubusercontent.com/caskroom/homebrew-cask/3c3268942ff163d917245fbc68d26a5bcddf91de/Casks/virtualbox.rb'
end

**Comment by paulhanssen** [comment]
Thanks @tas50  ... I'll close this now.
