### ISSUE TITLE
node["homebrew"]["user"] validation fails on non OSX hosts

### ISSUE THREAD

**Issue by jelmstrom** [chef-cookbooks/homebrew#132]
### Cookbook version
5.0.1

### Chef-client version
12.21.4

### Platform Details
Ubuntu 16.04

### Scenario:
Running chef client on an Ubuntu 16 machine that uses a recipe that has a dependency to homebrew 5.0.1 but no `node["homebrew"]["user"]` 

### Steps to Reproduce:
Create a cookbook that has a dependency on homebrew, run it on an ubuntu 16.04 machine without setting  the `node["homebrew"]["user"]` attribute

### Expected Result:
Should not install homebrew but not fail

### Actual Result:
Fails with error message `Homebrew owner is 'root' which is not supported`

After the release of 5.0.x, our recipes that are depending on hombrew can not be run on ubuntu 14 or 16 hosts, as the validation of the user to run as fails. Prior to this update the recipe ran fine on all platforms. 

This attribute should not be neccessary on hosts that are not concerned with hombrew, otherwise transient dependency concerns are 'leaked' up the chain.

**Comment by monkey1016** [comment]
An example of this is the `java` cookbook that depends on this cookbook:
agileorbit-cookbooks/java#456

**Comment by spion06** [comment]
seeing the issue too when testing on non-osx platforms

**Comment by tas50** [comment]
I'll have a fix out in the next hour for this

**Comment by tas50** [comment]
Give 5.0.2 a try and let me know if that works

**Comment by JordanFaust** [comment]
I can verify that this fix resolves the issue. I was seeing the exact same issue as we were using the java cookbook mentioned above.

**Comment by r4v5** [comment]
Any chance of adding a convergence of a basic runlist on a non-OSX OS to the regression suite to prevent this from recurring?

**Comment by jelmstrom** [comment]
Can confirm that v 5.0.3 resolves issue with our builds.

Thanks
