### ISSUE TITLE
Support git based homebrew taps

### ISSUE THREAD

**Issue by spkane** [chef-cookbooks/homebrew#79]
homebrew supports custom taps that can be installed from any repo using a command like:

```
brew tap my-internal/tap git@source.example.org:org/homebrew-my-internal.git
```

The homebrew cookbook does not support this functionality at the moment.

I wrote some code to fix this on my own private fork, but it wasn't backwards compatible as I changed the ['homebrew']['taps'] attribute into an array of hashes like this:

```
[
        { "name": "caskroom/cask" },
        { "name": "homebrew/dupes" },
        { "name": "homebrew/completions" },
        { "name": "custom-internal/tap",
          "repo": "git@ghe.example.com:org/homebrew-custom-internal.git"
        }
]
```

**Comment by tas50** [comment]
This has been released in 4.1!
