### ISSUE TITLE
need multipackage support

### ISSUE THREAD

**Issue by nathwill** [chef-cookbooks/homebrew#89]
it'd be great if homebrew_package had multipackage support. at present, homebrew cookbook's breaking the ability to rely on multipackage support, as described in https://github.com/chef-rbenv/ruby_rbenv/issues/139

**Comment by tas50** [comment]
@nathwill Are you using Chef 11 or 12?  If you're on 12 you shouldn't be running the package provider from within the cookbook.

**Comment by tas50** [comment]
I created a chef/chef issue for multipackage support in the homebrew package provider here https://github.com/chef/chef/issues/4441.  I'm going to close out this issue since it's really a chef-client problem.
