### ISSUE TITLE
New Upstream Behavior

### ISSUE THREAD

**Issue by bdwyertech** [chef-cookbooks/homebrew#99]
Today I noticed the following behavior after running `brew update`

```
==> Migrating /Library/Caches/Homebrew to /Users/bdwyer/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
```

Seems to be related to https://github.com/Homebrew/brew/commit/a9abbab9175379d990d49d06341c14579db92bb2

So what does this mean?  We can probably scrub out the following:
* https://github.com/chef-cookbooks/homebrew/blob/master/recipes/cask.rb#L23-L27

I say we let it milk a while before we pull this, the guard resource that's already there should prevent it from causing any havoc for now 😄

**Comment by tas50** [comment]
Released to supermarket
